### ISSUE TITLE
Automate fetch of data

### ISSUE THREAD

**Issue by piranna** [wallet77/nodejs-versions#13]
Data is outdated, there should be a nightly script updating the `allVersions.json` file.

**Comment by wallet77** [comment]
The file `allVersions.json` is requested every day in order to keep the cache up to date.
The TTL value is not editable by env var but we can eventually do a PR for that if you want to fetch data more often.

https://github.com/wallet77/nodejs-versions/blob/5d6ce8feaa0e8e1d0f4a02d214bd854ec5da02a9/src/constants.js#L5

**Comment by piranna** [comment]
> The TTL value is not editable by env var but we can eventually do a PR for that if you want to fetch data more often.

I would do it in a nightly basis instead, adjusted to the Node.js servers timezone. Anyway, the topic of this issue is that the branches at https://github.com/wallet77/nodejs-versions/branches show it has not been updated since December last year...

**Comment by piranna** [comment]
Maybe nightly script is not working? Or does I'm looking for in the wrong place?

**Comment by wallet77** [comment]
The file itself is generated on your system every day, there is an internal cache system that make the file expire.
It's not comited in the repo, so there is no need of a nightly script.

**Comment by piranna** [comment]
Is it a cache on my side? I though package could be used fully offline...

**Comment by wallet77** [comment]
Yes it's on your side, the module doesn't come with a version of the file containing versions.
This file is available online and is provided by the Node.js team.
